### ISSUE TITLE
Dactyl is using old std version

### ISSUE THREAD

**Issue by Penkie** [liamtan28/dactyl#14]
When running a basic dactyl application there's errors:

```error: TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname
                 ~~~
    at https://deno.land/std@0.51.0/path/win32.ts:911:18

TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname;
                 ~~~
    at https://deno.land/std@0.51.0/path/posix.ts:433:18

Found 2 errors.
```
Versions
```
deno 1.2.0
v8 8.5.216
typescript 3.9.2
```

std@0.51.0 is not compatible with 1.2.0 deno version.

**Comment by Crashou59** [comment]
same problem, please update std dependancies

**Comment by coroo** [comment]
Same problem. 

Found std not compatible version with deno v1.2.* at https://github.com/liamtan28/dactyl/blob/master/deps.ts#L11 line 11 to 13. Need review in PR https://github.com/liamtan28/dactyl/pull/15. 

Thank you

**Comment by mordeccai** [comment]
Why did you close this issue? It is not fixed
