### ISSUE TITLE
TS2349 when trying to run the example

### ISSUE THREAD

**Issue by lezsakdomi** [liamtan28/dactyl#8]
When trying to run the specified example (i.e. `deno run --allow-net --config=tsconfig.json https://deno.land/x/dactyl/example/index.ts`), I get:
```
error: TS2349 [ERROR]: This expression is not callable.
  Each member of the union type '{ <P extends Record<string | number, string | undefined> = Record<string | number, string | undefined>, S extends Record<string | number | symbol, any> = Record<string, any>>(name: string, path: stri
ng, ...middleware: RouterMiddleware<...>[]): Router<...>; <P extends Record<...> = Record<...>, S extends Record<...> ...' has signatures, but none of those signatures are compatible with each other.
      this[route.requestMethod](
      ~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/dactyl/Router.ts:74:7
```

`deno --version` says:
```
deno 1.0.2
v8 8.4.300
typescript 3.9.2
```

**Comment by liamtan28** [comment]
@lezsakdomi thank you - I’ll investigate shortly.

**Comment by lezsakdomi** [comment]
Ok, it seems like the following patch resolves the TS error:

```patch
Index: Router.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- Router.ts	(revision 1b6196bd874673fb0da816fb5910f92279ee1ffc)
+++ Router.ts	(date 1590937351102)
@@ -71,7 +71,8 @@
       }
 
       // Call routing function on OakRouter superclass
-      this[route.requestMethod](
+      const method: (name: string, middleware: (context: RouterContext) => Promise<void>) => void = this[route.requestMethod];
+      method(
         path,
         async (context: RouterContext): Promise<void> => {
           try {
```

Finally the server starts up, but dies immediately:
```
PS D:\Users\lezsa\IdeaProjects\dactyl> deno run --config .\example\tsconfig.json --allow-net .\example\index.ts
Compile file:///D:/Users/lezsa/IdeaProjects/dactyl/example/index.ts
______           _         _
|  _  \         | |       | |
| | | |__ _  ___| |_ _   _| |
| | | / _` |/ __| __| | | | |
| |/ / (_| | (__| |_| |_| | |
|___/ \__,_|\___|\__|\__, |_| FRAMEWORK
                      __/ |
                      |___/

Registered routes:

        /dinosaur
                [GET] /
error: Uncaught TypeError: Cannot read property '#useVerb' of undefined
    this.#useVerb(
         ^
    at get (https://deno.land/x/oak/router.ts:589:10)
    at file:///D:/Users/lezsa/IdeaProjects/dactyl/Router.ts:75:7
    at Map.forEach (<anonymous>)
    at Router.register (file:///D:/Users/lezsa/IdeaProjects/dactyl/Router.ts:64:17)
    at new Application (file:///D:/Users/lezsa/IdeaProjects/dactyl/Application.ts:21:19)
    at file:///D:/Users/lezsa/IdeaProjects/dactyl/example/index.ts:7:26
```

**Comment by lezsakdomi** [comment]
I've changed to `https://deno.land/x/oak@v4.0.0/mod.ts` in `deps.ts`. The _#useVerb_ issue persisted. Then I reverted the patch I sent above. Then it worked. Now IntelliJ IDEA's typescript service reports the TS2349 error, but somehow the example runs successfully even using `https://deno.land/x/oak@v4.0.0/mod.ts` i.e. the issue fixed for me magically somehow.

**Comment by lezsakdomi** [comment]
On a fresh repl.it environment and on my other project I still get the error above.

**Comment by lezsakdomi** [comment]
A file with the following contents compiles successfully:
```typescript
import "https://raw.githubusercontent.com/lezsakdomi/dactyl/fix-8-version-oak-400/mod.ts"
```

**Comment by liamtan28** [comment]
Thank you @lezsakdomi for spotting this - it wasn't my intention to rely on Oak master here, I will lock the version to 4.0.0 for now and upgrade when I have time. I suspect the Oak API will be a little unstable for the time being as Deno v1 just dropped.
